From node:18-alpine as Builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

From node:18-alpine as production

ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./

RUN npm ci --ignore-scripts

COPY --from=builder /app/dist ./

EXPOSE 5500 

CMD ["node","server.js"]